# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Start bash_completion
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# basic env
uname=$(uname)
if [ $uname == "Darwin" ];then
	export OS="Mac"
elif [ $uname == "Linux" ];then
	export OS="Linux"
else
	export OS="Unknown"
fi

export LANG='en_US.UTF-8'

# gcc env
# export GCC_ROOT=/usr/local/gcc
# export PATH=$GCC_ROOT/bin:$PATH
# export C_INCLUDE_PATH=$GCC_ROOT/include
# export CPLUS_INCLUDE_PATH=$GCC_ROOT/include/c++
# export LD_LIBRARY_PATH=$GCC_ROOT/lib
# export LIBRARY_PATH=

# java env
# export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
# export PATH=$JAVA_HOME/bin:$PATH

# golang env
# export GOPATH=~/Library/Gopath
# export WORKSPACE=~/workspace
# export PATH=~/Library/Gopath/bin:$PATH

# maven env
# export M3_HOME=/usr/local/Cellar/maven/3.6.3_1
# export PATH=$M3_HOME/bin:$PATH
# export MAVEN_OPTS="-Xms256m -Xmx1024m -Dfile.encoding=UTF-8"

SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi

# export http_proxy=http://proxy.zhenguanyu.com:8118
# export https_proxy=http://proxy.zhenguanyu.com:8118

# Source diy definitions
if [ -f ~/.bashrc.inc ]; then
	. ~/.bashrc.inc
fi

